# -------------------------------------------------- #
#        DimensionsReset Config - Reorganized        #
# -------------------------------------------------- #

# Controls the fully automated, recurring dimension resets.
automated_resets:
  enabled: true
  schedules:
    - id: "weekly_end_reset"
      dimension: "the_end"
      announcement_time: "1h"
      schedule:
        type: "INTERVAL"
        value: "7d"

# A list of dimensions that reset when using '/dr reset all'.
reset-all-dimensions:
  - "the_end"
  - "the_nether"

# --- Message Configuration ---

dimension_reset_messages:
  confirmation:
    required: "&e&lWARNING! &7You are about to immediately reset &e%dimension%&7. Type &a/dr confirm &7to proceed."
    success: "&aConfirmation received. Initiating reset for &e%dimension%&a..."
    expired: "&cConfirmation expired. Reset for &e%dimension%&c has been cancelled."
    not_required: "&cThere is no pending reset to confirm."
  reset_now: "&c&lThe %dimension% dimension is being reset NOW!"
  reset_scheduled: "&a&lThe %dimension% dimension will be reset in %time%."
  reset_cancelled: "&eThe scheduled reset for %dimension% has been cancelled."
  status_scheduled: "&aA reset for %dimension% is scheduled in &e%time%&a."
  status_not_scheduled: "&eThere is no reset currently scheduled for %dimension%."

  # After a dimension is reset, the plugin will schedule a server restart to ensure
  # the new world is loaded correctly and all portals work.
  restart_manager:
    # Enable the automatic restart after a reset.
    # ONLY TURN TO 'FALSE' IF YOU KNOW WHAT YOU ARE DOING!
    enabled: true
    # Delay in seconds before the server restarts.
    delay: 30
    # The message broadcast to all players before the restart.
    broadcast_message: "&c&lThe dimension has been reset! The server will restart in %time% seconds to load the new world."

wilderness_reset:
  wand_give: "&d✨ &aYou have received the Protection Wand! &7(Left-click for Pos1, Right-click for Pos2)"
  pos1_set: "&aPosition 1 set. &7(&e%location%&7)"
  pos2_set: "&aPosition 2 set. &7(&e%location%&7)"
  region_saved: "&a✅ Protected region '&e%name%&a' has been saved."
  region_deleted: "&c🗑️ Protected region '&e%name%&c' has been deleted."
  region_list_header: "&6--- Saved Protected Regions ---"
  region_list_item: "&e- %name%"
  region_list_empty: "&eYou have not saved any protected regions yet."
  error_no_selection: "&cYou must select two positions with the wand first!"
  error_region_exists: "&cRegion named '&e%name%&c' already exists."
  error_region_not_found: "&cCould not find a region named '&e%name%&c'."
  reset:
    confirm1: "&e&lWARNING! &7You are about to reset the wilderness for world '&e%world%&7'. This cannot be undone. Type &a/dr confirm &7to proceed."
    confirm2: "&c&lFINAL WARNING! &4This is irreversible. &7Type &a/dr lastconfirm &7to permanently delete the chunks."
    players_moved: "&aThe wilderness is resetting! You have been moved to a safe location."
    start: "&aWilderness reset initiated for '&e%world%&a'. Deleting unprotected chunks..."
    complete: "&aWilderness reset complete! Players have been returned."

preview:
  enter_message: "&aYou are now in preview mode for &e%dimension%&a. Use &e/dr preview exit &ato return."
  exit_message: "&aYou have exited preview mode and returned to your original location."
  seed_message: "&aThe server's main world seed is: &e%seed%"
  error_not_in_preview: "&cYou are not currently in preview mode."
  error_already_in_preview: "&cYou are already in preview mode. Use /dr preview exit."
  error_dimension_not_found: "&cThe &e%dimension% &cdimension is not loaded. Have a player visit it to load it, then try again."
  error_players_only: "&cThis command can only be run by a player."

generic_messages:
  config_reloaded: "&aDimensionsReset configuration has been reloaded."
  error_no_permission: "&cYou do not have permission to use this command."
  error_invalid_time: "&cInvalid time format. Use a format like '1h30m10s'."

# --- Functional Configuration ---

countdown_broadcast_times:
  - 3600, 1800, 600, 60, 30, 10, 5, 4, 3, 2, 1

sounds:
  reset_scheduled: "entity.player.levelup"
  countdown_tick: "block.note_block.hat"
  reset_success: "entity.wither.death"
