# -------------------------------------------------- #
#             DimensionsReset Config                 #
# -------------------------------------------------- #

# Settings for the confirmation system for '/dr reset now'
confirmation:
  # Message sent when confirmation is required.
  required_message: "&e&lWARNING! &7You are about to reset The End immediately. This cannot be undone. Type &a/dr confirm &7within 15 seconds to proceed."
  # Message sent if the user confirms successfully.
  success_message: "&aConfirmation received. Initiating reset..."
  # Message sent if the 15-second confirmation window expires.
  expired_message: "&cConfirmation expired. The reset has been cancelled."
  # Message sent to a user who types /dr confirm when it's not needed.
  not_required_message: "&cThere is nothing to confirm."

# Broadcast messages for server-wide announcements
messages:
  reset-now: "&c&lThe End dimension is being reset NOW!"
  reset-scheduled: "&a&lThe End dimension will be reset in %time%."
  reset-cancelled: "&eThe scheduled reset for The End has been cancelled."
  # Message for the /dr status command
  status-scheduled: "&aA reset for The End is scheduled in &e%time%&a."
  status-not-scheduled: "&eThere is no reset currently scheduled for The End."
  # Message sent when the config is reloaded
  config-reloaded: "&aDimensionsReset configuration has been reloaded."
  # Generic error messages
  error-no-permission: "&cYou do not have permission to use this command."
  error-invalid-time: "&cInvalid time format. Use a format like '1h30m10s'."

# Add this new 'preview' section to your config.yml

preview:
  # Message sent when a player enters preview mode.
  enter_message: "&aYou are now in preview mode. Use &e/dr preview exit &ato return."
  # Message sent when a player leaves preview mode.
  exit_message: "&aYou have exited preview mode and have been returned to your original location."
  # Message sent when displaying the world seed. %seed% is the placeholder.
  seed_message: "&aThe next End dimension will be generated using the main world's seed: &e%seed%"
  # Error messages
  error_not_in_preview: "&cYou are not currently in preview mode."
  error_already_in_preview: "&cYou are already in preview mode. Use /dr preview exit to leave."
  error_end_not_found: "&cThe End is not currently loaded in memory. Please have a player visit The End to load it, then try again."
  error_players_only: "&cThis command can only be run by a player."

# A list of times (in seconds) before the reset to broadcast a countdown message.
# You can add or remove any times you want.
countdown_broadcast_times:
  - 3600  # 1 hour
  - 1800  # 30 minutes
  - 600   # 10 minutes
  - 300   # 5 minutes
  - 60    # 1 minute
  - 30    # 30 seconds
  - 10    # 10 seconds
  - 5
  - 4
  - 3
  - 2
  - 1

# Sound effects played for all players during key events.
# Find sound names here: https://minecraft.wiki/w/Sounds.json
sounds:
  # Sound played when a reset is first scheduled.
  reset_scheduled: "entity.player.levelup"
  # Sound played during the final countdown (e.g., 10, 9, 8...)
  countdown_tick: "block.note_block.hat"
  # Sound played at the exact moment the dimension is reset.
  reset_success: "entity.wither.death"
