# This is the modern Paper plugin file.
# Paper servers prioritize this file over plugin.yml.
name: DimensionsReset
version: 'v1.0' # This gets the version from your pom.xml during build
main: com.example.dimensionsreset.DimensionsReset
api-version: '1.21'
author: Mike4947
website: https://github.com/Mike4947/Dimensions-Reset
description: A plugin to reset dimensions in Minecraft.

commands:
  dr:
    description: Main command for DimensionsReset.
    usage: /dr reset the_end <time|now>
    permission: dimensionsreset.admin

permissions:
  dimensionsreset.admin:
    description: Allows user to use the /dr command to reset dimensions.
    default: op