# This version uses spaces ONLY. No tabs.
name: DimensionsReset
version: '${project.version}'
main: com.example.dimensionsreset.DimensionsReset
api-version: '1.21'
author: Mike4947
website: https://github.com/Mike4947/Dimensions-Reset
description: A plugin to reset dimensions in Minecraft.

# The 'commands' block has been removed.

permissions:
  dimensionsreset.admin:
    description: Allows use of reset, cancel, and status commands.
    default: op
  dimensionsreset.reload:
    description: Allows use of the /dr reload command.
    default: op
