# This file is for classic Bukkit/Spigot command registration.
name: DimensionsReset
version: 'v1.0'
main: com.example.dimensionsreset.DimensionsReset
api-version: '1.21'
# We define the commands here for Bukkit's command system to see.
commands:
  dr:
    description: Main command for DimensionsReset.
    usage: "/dr <reset|cancel|confirm|status|reload>"
    aliases: [dims, dreset]
    permission: dimensionsreset.admin
