# This file is for modern Paper-specific metadata.
# Commands are now defined in plugin.yml to ensure compatibility.
name: DimensionsReset
version: '1.4.0-build(4)'
main: com.example.dimensionsreset.DimensionsReset
api-version: '1.21'
author: Mike4947
website: https://github.com/Mike4947/Dimensions-Reset
description: A plugin to reset dimensions in Minecraft.

# Notice the 'commands' block is GONE from this file.

permissions:
  dimensionsreset.admin:
    description: Allows use of reset, cancel, and status commands.
    default: op
  dimensionsreset.reload:
    description: Allows use of the /dr reload command.
    default: op
  dimensionsreset.preview:
      description: Allows use of the /dr preview command.
      default: op